### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by slyfur** [Aycn0/dashing-btc-widget#3]
What would it take to include the ending price for the previous day just below the current price? I really like this widget. It works well. I have tried to add this feature, but I'm just not getting something.  Thanks!

**Comment by 3E5F** [comment]
I can look into it, it depends if the API that I'm using provides that information. But I think timezones will play a big part in it. I'll play around with it and keep you posted within 24 hours.

**Comment by Aycn0** [comment]
Also, there is no "ending price" for bitcoin. I think it would be better to get the price of 24 hours ago.

**Comment by 3E5F** [comment]
Looking through available apis, the closest one would be coindesks api. Here's what I can push. Any ideas or recommendations?
![screen shot 2018-02-12 at 11 25 13 pm](https://user-images.githubusercontent.com/5965527/36137917-2811cf24-104c-11e8-84c7-0ddd7caf2335.png)

**Comment by slyfur** [comment]
Thanks for the quick response. That's exactly the look that I was thinking about. I was just looking for some reference point when I see the current price.  I had been testing passing a hard-coded date to the Coinbase API.  I don't know if it's picking the price at the end of the day or the beginning.  [https://developers.coinbase.com/api/v2#get-spot-price](https://developers.coinbase.com/api/v2#get-spot-price)

**Comment by 3E5F** [comment]
I'll push this for now. Once we find a better api, we'll make some changes

**Comment by 3E5F** [comment]
Added feature in commit 1e901b18bb22125a9ed8b86c718bc9225cbbf8d9

**Comment by slyfur** [comment]
I'm not sure if saying "thank you" violates etiquette (or re-opens the issue), but "thank you!" It works perfectly!
